# Generated by Django 3.2.15 on 2022-09-30 17:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0013_auto_20190929_0136'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='PRDImage2',
            field=models.ImageField(blank=True, null=True, upload_to='prodcut/', verbose_name='Image'),
        ),
        migrations.AddField(
            model_name='product',
            name='PRDImage3',
            field=models.ImageField(blank=True, null=True, upload_to='prodcut/', verbose_name='Image'),
        ),
    ]
